

services:

  database:
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "${FASTAPI_PORT}:3000"
    volumes:

    depends_on:
      - database